version: "2"
services:
    nginx:
        build: ./nginx
        volumes:
        - ./nginx/nginx/:/etc/nginx
        ports:
        - "8080:80"
        depends_on:
        - nodered
        - mqtt

    nodered:
        build: ./node_red
        #image: c2b60d7672e2
        ports:
        - "8088:8088"
        volumes:
        - ./node_red/src:/src
        - ./node_red/src/node-red-contrib-svg-storage:/data/node_modules/node-red-contrib-svg-storage
        depends_on:
        - storage

    storage:
        build: ./storage-api
        ports:
        - "8100:8100"
        depends_on:
        - mongodb

    crud:
        build: ./crud
        ports:
        - "8090:8090"
        depends_on:
        - mongodb

    mongodb:
        image: mongo
        ports:
        - "27017:27017"

    mqtt:
        #build: ./mosquitto
        image: jllopis/mosquitto
        volumes:
        - ./mosquitto/mosquitto.d/:/etc/mosquitto.d/
        #- ./mosquitto/:/mosquitto/config
        ports:
        #- "9001:9001"
        - "1883:1883"
        - "9883:9883"